import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by next app",
};


export default function Page() {
  return (
    <div>Page</div>
  );
}